# DBを使うためには、ユーザ名やパスワードの設定が必要である.

# PostgreSQLの主な環境変数は
# - POSTGRES_DB : データベース名
# - POSTGRES_USER : データベースのユーザ名
# - POSTGRES_PASSWORD : データベースのパスワード


services:
  db:
    image: postgres:14.2
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
