services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-container
    ports:
      - "5000:5000" # 「http://localhost:5000/」
    volumes:
      - ./src:/usr/src/app
    #tty:
    #  true
